name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: brew install ninja
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release --parallel
      - run: |
          mkdir -p dist
          cp build/bin/buildtemplate_app dist/buildtemplate-macos
          cd dist && zip -r ../buildtemplate-macos.zip buildtemplate-macos
      - uses: actions/upload-artifact@v4
        with:
          name: buildtemplate-macos
          path: buildtemplate-macos.zip

  windows:
    runs-on: windows-latest
    strategy:
      matrix: { arch: [ Win32, x64, ARM64 ] }
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.arch }}
      - run: cmake --build build --config Release --parallel
      - shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item "build/Release/buildtemplate_app.exe" "dist/buildtemplate-windows-${{ matrix.arch }}.exe"
          Compress-Archive -Path dist/buildtemplate-windows-${{ matrix.arch }}.exe -DestinationPath buildtemplate-windows-${{ matrix.arch }}.zip -Force
      - uses: actions/upload-artifact@v4
        with:
          name: buildtemplate-windows-${{ matrix.arch }}
          path: buildtemplate-windows-${{ matrix.arch }}.zip

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release --parallel
      - run: |
          mkdir -p dist
          cp build/bin/buildtemplate_app dist/buildtemplate-linux
          cd dist && tar czf ../buildtemplate-linux.tar.gz buildtemplate-linux
      - uses: actions/upload-artifact@v4
        with:
          name: buildtemplate-linux
          path: buildtemplate-linux.tar.gz
